name: CI Pipeline

on:
  pull_request:
    branches:
        - main
  push:
    branches: 
        - "**"

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: team2-front-app-pipeline

jobs:
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Run Biome Linting
          run: npm run lint

        - name: Run Biome Formatting Check
          run: npm run format:check

    accessibility:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Run Accessibility Tests
          run: npm run test:pa11y:local

    build:
        needs: [code-quality, accessibility]
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Build Application
          run: npm run build

    containerise:
        needs: build
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Azure Login (Service Principal)
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Build Docker Image
          run: docker build -t ${{ env.IMAGE_NAME }}:latest .

        - name: Tag Docker Image
          run: |
            docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            docker tag ${{ env.IMAGE_NAME }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        - name: Push Docker Image
          run: |
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
